### ISSUE TITLE
Add CSS to .less files

### ISSUE THREAD

**Issue by amdrew** [postpromoterpro/ppp-site#2]
@cklosowski can you put any CSS that you've added so far into the child theme's .less files and then recompile? Or maybe just add everything to one custom file. It looks like you may have placed them in the style.css file which will be overridden once the .less files are compiled, hence losing all your changes.

**Comment by cklosowski** [comment]
@sumobi sure, any changes I need to make those styles work in `.less`?

**Comment by cklosowski** [comment]
Done in `develop`.
